@startuml
scale 350 width

[*] --> LineStart

LineStart --> [*] : (1)

LineStart --> CodeLine : (2)
CodeLine -up-> LineStart : (3)

LineStart --> CommentLine : (4)
CommentLine -up-> LineStart : (5)


state CommentLine {

  [*] -right-> Begin

  Begin -> Rest : (6)
  Begin --> [*] : (7)

  Rest --> Rest : (8)
  Rest --> [*] : (9)

}
@enduml
